### ISSUE TITLE
Snow Leopard

### ISSUE THREAD

**Issue by davidmcraejr** [evan/bleak_house#2] opened 2010-04-22 19:41 UTC
I get bellow when trying to install on Snow Leopard:

gcc -arch i386 -arch x86_64 -g -Os -pipe -fno-common -DENABLE_DTRACE -pipe -fno-common    -DRUBY_EXPORT   -L. -arch i386 -arch x86_64    main.o  -lruby-static -lpthread -ldl -lobjc -lpthread -ldl   -o ruby
-%{ BUILDING SNAPSHOT }%-
sh: ruby-bleak-house: command not found

Any ideas?

**Comment by siggy** [comment] 2010-05-06 05:37
Looks like ruby-bleak-house is not found in the path after compilation, I modified my extconf.rb to get past this:

```
+require 'rbconfig'
…
-BleakHouse.execute("ruby-bleak-house build_snapshot.rb >> #{BleakHouse::LOGFILE} 2>&1")
+BleakHouse.execute("#{Config::CONFIG['bindir']}/ruby-bleak-house build_snapshot.rb >> #{BleakHouse::LOGFILE} 2>&1")
```

Unfortunately I then run into this:

```
build_snapshot.rb:1: warning: already initialized constant RUBY_VERSION
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin10.0/etc.bundle: [BUG] Segmentation fault
ruby 1.8.7 (2009-06-12 patchlevel 905) [universal-darwin10.0]

Abort trap
```

**Comment by tra** [comment] 2010-05-12 21:26
Anyone have a fix for this?

**Comment by NullVoxPopuli** [comment] 2010-06-24 16:31
Use the latest Snow Leopard. mine just worked

**Comment by tfe** [comment] 2010-09-02 08:51
I'm using the latest Snow Leopard and it's not just working. :-(

I tried siggy's suggestion with the same result.

**Comment by nelsnelson** [comment] 2010-10-14 16:40
I am experiencing the same problem reported by dmac81.  Using Snow Leopard 10.6.4.

sh: ruby-bleak-house: command not found

Along with dozens of Makefile warnings.  :-(

**Comment by namxam** [comment] 2010-10-18 20:05
Yep, I can confirm the same with the latest SnowLeopard and "ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]"

**Comment by j1n6** [comment] 2010-12-31 07:04
The best way to install Ruby and Gems on Snow Leopard is either configure/make/make install your own Ruby and Gems instead of using system default, or try to use MacPorts.   

I ran into the same issues mentioned above. I compiled my own version of ruby and installed it /usr/local/bin/ . Then the instructions on the home page works!

**Comment by skyxie** [comment] 2011-06-09 20:29
@sIggy is right, the "sh: ruby-bleak-house: command not found" is caused by ruby-bleak-house not appearing in the PATH. 

I'm on Snow Leopard and I have ruby installed under /System/Library/... and /usr/bin/ruby is a sym-link to the actual binary. When the ruby-bleak-house binary is installed, it is installed alongside the actual ruby binary in /System/Library/..., but a similar sym-link is not made for the ruby-bleak-house binary and it does not appear in the PATH. I just added a sym-link /usr/bin/ruby-bleak-house to the actual binary.

But now I'm just experiencing the same problem as @sIggy...

[EDIT] I was able to fix this problem and get it working by compiling my own version of Ruby, but I hope this is not the only solution?

**Closed as completed** 2013-06-19 07:19 UTC
